### PR TITLE
Add a default python .gitignore

### PR DESCRIPTION
**Pull request by HarikalarKutusu**
This adds a default python .gitignore taken from https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore

Otherwise, local clones get dirty with __pycache__...

### CODE REVIEW

**Review by HarikalarKutusu — COMMENTED** [review]
I think this is the only one

**Comment by ftyers** [comment]
Hmm, it's still reporting conflicts...

**Comment by ftyers** [comment]
Let's try this!

**Comment by HarikalarKutusu** [comment]
I could not find the reason, did you?

**Comment by ftyers** [comment]
I didn't, I just resolved it manually. :)

**Pull request merged**
