### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by meghavarshini**

### CODE REVIEW

**Comment by meghavarshini** [comment]
edited alphabet.txt to split diacritics linewise.

**Comment by ftyers** [comment]
Thanks @meghavarshini, would this require different processing in order to use? e.g. the [code that loads the alphabet](https://github.com/ftyers/commonvoice-utils/blob/main/cvutils/alphabet.py) would need to change too no?

**Comment by meghavarshini** [comment]
> Thanks @meghavarshini, would this require different processing in order to use? e.g. the [code that loads the alphabet](https://github.com/ftyers/commonvoice-utils/blob/main/cvutils/alphabet.py) would need to change too no? Have you tested it to see if it works?

I have not tested it, no. Since the alphabet is now split by line, the detection may require the document to be read linewise. I will ask my collaborator to take a look. For some reason, same line diacritics are not being read as individual characters, hence the spacing. Please allow my collaborator some time to test this! 

Do you think it would be better to keep this patch separate until then?

**Comment by HarikalarKutusu** [comment]
@meghavarshini 's  collaborator here :) A couple of things:

1. Common Voice Utils / covo needs the alphabet to be in one line, without the leading space, as the alphabet.py here handles it. Changing that format would affect all languages.
2. On the other hand, Coqui needs each char on a new line, with the first line being a space. After speaking to @ftyers I learned that such a format can be created easily with covo.
```
covo alphabet hi > alphabet.txt
```
After I changed my workflow to using covo, it came out in the correct format as requested by Coqui.
3. The diacritics, when put one after another get jumbled into a single character. That may be a kerning issue thou, as they seem to be handled well by covo.
4. I could feed the alphabet to Coqui, it is training now. On the first run it complained that a character is missing, you might like to look into it: 
> ऋ

I propose:
* Omit this PR
* Check the missing char and add it in a new PR, if missing.

Thank you both :)
Bülent Özden

**Comment by meghavarshini** [comment]
Thanks @HarikalarKutusu. I appreciate your response and shall do as asked.

**Comment by ftyers** [comment]
I've added the `U+090B DEVANAGARI LETTER VOCALIC R` ऋ in d94a024.

**Pull request closed without merging**
